#!/usr/bin/env python3
"""Emit the model-facing vocabulary FROM `register.py`. Nobody types it twice.

This is half of the answer to #97 item 3. The other half lives in the suite,
which regenerates this text and refuses anything but byte-identity.

Why this shape and not "the prose points at the template": pointing only works
if the pointer's target is the template itself, and the template is 96 KB of
CSS and JS. Nobody reads that to learn twelve names, so somebody writes a
summary, and the summary is the thing that drifts. That is not a hypothesis --
it is the measured path slideless took, with one of its own references
admitting it deleted two sections for contradicting the engine.
"""
import pathlib

from register import REGISTER, BEATS, INLINE, ZONE_PCT

HERE = pathlib.Path(__file__).resolve().parent
BEGIN = "<!-- VOCABULARY: begin (generated by vocab.py — do not edit) -->"
END = "<!-- VOCABULARY: end -->"


def _row(name, spec):
    req = " · ".join(f"`{f}`" for f in spec["fields"]) or "—"
    opt = " · ".join(f"`{f}`" for f in spec["opt"]) or "—"
    return name, req, opt


def _ceil(spec):
    """The character budget, one entry per text ROLE -- not per field.

    `parts` carries three strings inside one `items`, and the register's ceiling
    names `title` and `body`, which are positions in that item rather than keys
    of the block. Calling this column "por campo" would be a name that is wrong
    for five of the eight, which is how a reader learns to stop trusting a
    generated table.
    """
    return " · ".join(f"`{k}` {v}" for k, v in spec["ceil"].items()) or "—"


def render():
    out = [BEGIN, ""]

    # NO IDENTIFIER EVER GETS A PORTUGUESE NICKNAME. A translated synonym is a
    # SECOND NAME for the same thing, and a second name is precisely what this
    # document exists to prevent. The prose is Portuguese; the name of the
    # piece is the identifier, in English (premise 10).
    out.append(f"**`beat` — {len(BEATS)} tipos.** Um `beat` é um trecho da "
               "coluna de leitura. Ele **não é uma página**: nada no documento "
               "desenha uma fronteira nele, e o número de ordem é derivado "
               "pelo construtor — o modelo nunca numera nada.")
    out.append("")
    out.append("| `beat` | obrigatório | opcional |")
    out.append("|---|---|---|")
    for name, spec in BEATS.items():
        n, req, opt = _row(name, spec)
        out.append(f"| `{n}` | {req} | {opt} |")
    out.append("")

    figs = [k for k, s in REGISTER.items() if s["lit"]]
    out.append(f"**`block` — {len(REGISTER)} tipos.** Um `block` é evidência "
               "desenhada a partir de dado. O modelo escolhe o nome e entrega "
               "os campos; o markup é do motor. "
               f"Os {len(figs)} marcados `figure` podem ocupar a faixa grudada "
               "no topo, porque têm partes que um `beat` acende.")
    out.append("")
    out.append("| `block` | obrigatório | opcional | `figure` |")
    out.append("|---|---|---|---|")
    for name, spec in REGISTER.items():
        n, req, opt = _row(name, spec)
        out.append(f"| `{n}` | {req} | {opt} | {'sim' if spec['lit'] else '—'} |")
    out.append("")

    out.append(f"**Os tetos.** Um orçamento de caracteres por papel de "
               "texto, medido contra a **zona de leitura** — a altura da "
               f"janela menos a faixa da figura e o véu do rodapé, ou "
               f"**{ZONE_PCT}%** dela. Estourar um teto vira **mais um "
               "`block`**, nunca texto compactado. O construtor **não recusa "
               "por teto**: quem reprova é a página, e é por isso que o "
               "número está publicado aqui em vez de descoberto lá.")
    out.append("")
    out.append("| `block` | itens | teto de caracteres | zonas |")
    out.append("|---|---|---|---|")
    for name, spec in REGISTER.items():
        count = spec.get("count")
        out.append(f"| `{name}` | {count if count else '—'} | "
                   f"{_ceil(spec)} | {spec['zones']} |")
    out.append("")
    out.append("Quem cabe em **uma** zona é desenhado para ser visto inteiro "
               "de uma vez — ver inteiro é a razão de desenhá-lo, e o que não "
               "coube não vira letra menor. Quem pode correr **duas** é lido "
               "de cima para baixo, e rolar é o movimento deste formato.")
    out.append("")

    inline = " · ".join(f"`<{t}>`" for t in INLINE)
    out.append(f"**Markup em linha permitido dentro de qualquer texto:** "
               f"{inline}. Qualquer outra tag, e qualquer `style=` ou "
               "`class=`, é recusada pelo construtor com mensagem que nomeia "
               "o próprio conserto.")
    out.append("")
    out.append("**`lit`:** qualquer `beat` pode trazer `lit`, uma lista de "
               "índices de 1 a N das partes do `figure`. É o único número que "
               "o modelo escreve, e o construtor recusa índice que não tem o "
               "que acender.")
    out.append("")
    out.append(END)
    return "\n".join(out)


def current(path):
    """The generated block as it stands in `path`, or None if absent."""
    text = pathlib.Path(path).read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        return None
    head, rest = text.split(BEGIN, 1)
    body, tail = rest.split(END, 1)
    return BEGIN + body + END


def write(path):
    p = pathlib.Path(path)
    text = p.read_text(encoding="utf-8")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    p.write_text(head + render() + tail, encoding="utf-8")


if __name__ == "__main__":
    import sys
    target = HERE.parent / "VOCABULARY.md"
    if "--write" in sys.argv:
        write(target)
        print(f"{target.name}: regenerated")
    else:
        print(render())
