'use strict';
/**
 * Diagrams broken on purpose — the validator's negative control.
 *
 * #11's `check-boundary.cjs` established the convention and it holds here: a
 * check is only proven when it FAILS what it should fail. A validator that has
 * only ever been tested against good drawings and never failed is
 * indistinguishable from a validator that does not run — and the second one
 * also gives a green suite.
 *
 * Each case below breaks ONE named thing and declares which check has to
 * flag it. The assertion is one of inclusion, not equality: breaking a node's
 * containment fires A4.1, A4.2 and A4.4 at the same time, because the three
 * look at the same geometry from different angles, and demanding that only
 * one fire would be demanding that the rubric have no redundancy — it does,
 * on purpose.
 *
 * The plans are built by hand, not generated by the engine, for two reasons:
 * the engine does not know how to produce these defects (not producing them
 * is its job), and a literal plan leaves the defect visible in the file's own
 * review.
 *
 * Reminder that plan geometry is RELATIVE TO THE PARENT: a child's `geo` is
 * measured from the parent's corner, and that is exactly what makes it easy
 * to write a child that escapes the box without noticing.
 */

const GRAY = '#232F3E';

/** Container style (containment group). */
const group = (stroke = '#00A4A6', fill = 'none') =>
  `points=[[0,0],[1,1]];outlineConnect=0;gradientColor=none;html=1;whiteSpace=wrap;fontSize=12;` +
  `container=1;pointerEvents=0;collapsible=0;recursiveResize=0;shape=mxgraph.aws4.group;` +
  `grIcon=mxgraph.aws4.group_vpc;strokeColor=${stroke};fillColor=${fill};verticalAlign=top;align=left;spacingLeft=30;`;

/** Service icon style (leaf). */
const icon = (fill = '#ED7100', res = 'lambda') =>
  `sketch=0;outlineConnect=0;fontColor=${GRAY};gradientColor=none;fillColor=${fill};strokeColor=#ffffff;` +
  `dashed=0;verticalLabelPosition=bottom;verticalAlign=top;align=center;html=1;fontSize=12;fontStyle=0;` +
  `aspect=fixed;shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.${res};`;

/** Band style (overlay), dashed, unfilled. */
const band = (stroke = '#7AA116') =>
  `fillColor=none;strokeColor=${stroke};dashed=1;verticalAlign=top;fontStyle=0;fontColor=${stroke};` +
  `whiteSpace=wrap;html=1;container=1;pointerEvents=0;collapsible=0;recursiveResize=0;labelBackgroundColor=#FFFFFF;`;

const edge = (extra = '') =>
  `edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeColor=${GRAY};strokeWidth=1.6;` +
  `endArrow=blockThin;endFill=1;fontSize=12;fontColor=${GRAY};labelBackgroundColor=#FFFFFF;${extra}`;

const v = (id, parent, x, y, w, h, style, label = id) => ({ kind: 'vertice', id, parent, label, style, geo: { x, y, w, h } });
const e = (id, from, to, label, style = edge(), points = []) => ({ kind: 'edge', id, parent: '1', from, to, label, style, points });

/** Packs cells into a plan, with the model embedded the way the engine does. */
function build(id, cells, model, width = 900, height = 700) {
  return {
    layoutPlan: {
      id, name: id, background: '#FFFFFF', width, height,
      cells: [
        ...cells,
        {
          kind: 'vertice', id: 'panlabs-modelo', parent: '1', label: '', visible: false,
          style: 'text;html=1;', geo: { x: 0, y: 0, w: 1, h: 1 },
          data: { panlabsModelo: JSON.stringify(model) },
        },
      ],
    },
    model,
  };
}

// A minimal model that types the ids used in the cases.
const mod = (nodes, extra = {}) => ({
  schema: 'panlabs-aws-diagrams/model@1', id: 'broken', title: 'Broken case',
  view: 'technical', nodes, ...extra,
});

const CASES = [

  {
    name: 'node drawn inside the wrong VPC',
    because: 'the VPC box IS the network boundary; the drawing asserts a membership the model denies',
    expect: ['A4.2', 'A4.4'],
    ...build('a4.2', [
      v('vpc-a', '1', 60, 60, 300, 260, group()),
      v('vpc-b', '1', 460, 60, 300, 260, group('#C925D1')),
      // child of vpc-a, but with geo that throws it inside vpc-b
      v('srv', 'vpc-a', 460, 100, 78, 78, icon()),
    ], mod([
      { id: 'vpc-a', kind: 'vpc' }, { id: 'vpc-b', kind: 'vpc' },
      { id: 'srv', kind: 'service', service: 'lambda', inside: 'vpc-a' },
    ])),
  },

  {
    name: 'edge crossing a VPC it neither leaves from nor goes to',
    because: 'suggests a nonexistent network path between two networks that do not talk to each other',
    expect: ['A5.5'],
    ...build('a5.5', [
      v('vpc-mid', '1', 300, 60, 260, 300, group()),
      v('inside', 'vpc-mid', 90, 120, 78, 78, icon('#8C4FFF', 'vpc_endpoints')),
      v('left', '1', 60, 160, 78, 78, icon()),
      v('right', '1', 700, 160, 78, 78, icon('#C925D1', 'rds')),
      // the polyline cuts through the vpc-mid box horizontally
      e('e1', 'left', 'right', 'replica', edge(), [{ x: 200, y: 199 }, { x: 660, y: 199 }]),
    ], mod([
      { id: 'vpc-mid', kind: 'vpc' },
      { id: 'inside', kind: 'service', service: 'vpc_endpoints', inside: 'vpc-mid' },
      { id: 'left', kind: 'service', service: 'lambda' },
      { id: 'right', kind: 'service', service: 'rds' },
    ], { edges: [{ from: 'left', to: 'right', label: 'replica' }] })),
  },

  {
    name: 'AZ band embracing a node that is not a member of it',
    because: 'the band asserts a shared attribute — saying an EC2 is in an AZ it is not in is the same lie as A4.2, by another path',
    expect: ['F1'],
    ...build('f1', [
      v('az-a', '1', 60, 60, 320, 300, band()),
      v('member', '1', 100, 140, 78, 78, icon()),
      v('outsider', '1', 240, 140, 78, 78, icon('#C925D1', 'rds')),
    ], mod([
      { id: 'member', kind: 'service', service: 'lambda' },
      { id: 'outsider', kind: 'service', service: 'rds' },
    ], { bands: [{ id: 'az-a', members: ['member'], label: 'Availability Zone · us-east-1a' }] })),
  },

  {
    name: 'band that declares a member and does not embrace it',
    because: 'the other side of the same defect: the model asserts the attribute and the drawing does not show it',
    expect: ['F1'],
    ...build('f1-b', [
      v('asg', '1', 60, 60, 200, 200, band()),
      v('inside', '1', 100, 120, 78, 78, icon()),
      v('forgotten', '1', 500, 120, 78, 78, icon()),
    ], mod([
      { id: 'inside', kind: 'service', service: 'ec2' },
      { id: 'forgotten', kind: 'service', service: 'ec2' },
    ], { bands: [{ id: 'asg', members: ['inside', 'forgotten'], label: 'Auto Scaling group' }] })),
  },

  {
    name: 'edge crossing the band of a zone it does not touch',
    because: 'it is A5.5 by the other class of box: the line draws the path INSIDE a zone it does not pass through. ' +
      'A5.5 would never catch it — it sweeps `scene.groups`, and a band is not a group. ' +
      'It is the drawing that the #21 fallback existed to prevent, and today\'s engine does not produce it ' +
      '(measured on a full 3-to-6-zone mesh): that is why the proof body is planted here.',
    expect: ['F2'],
    ...build('f2', [
      v('az-a', '1', 60, 60, 200, 300, band()),
      v('az-b', '1', 300, 60, 200, 300, band()),
      v('az-c', '1', 540, 60, 200, 300, band()),
      v('n-a', '1', 100, 160, 78, 78, icon()),
      v('n-b', '1', 340, 160, 78, 78, icon()),
      v('n-c', '1', 580, 160, 78, 78, icon()),
      // straight from end to end, through the middle band — the trace that #21
      // measured as `A5.5` = 1 in the `b-az-linha-fluxo-horizontal` drawing
      e('replica', 'n-a', 'n-c', 'replica', edge(), [{ x: 250, y: 199 }, { x: 520, y: 199 }]),
    ], mod([
      { id: 'n-a', kind: 'service', service: 'ec2' },
      { id: 'n-b', kind: 'service', service: 'ec2' },
      { id: 'n-c', kind: 'service', service: 'ec2' },
    ], {
      edges: [{ from: 'n-a', to: 'n-c', label: 'replica' }],
      // each band declares exactly its own node and embraces it: F1 stays clean
      // on purpose, so this case's red is ONLY F2
      bands: [
        { id: 'az-a', members: ['n-a'], label: 'Availability Zone · us-east-1a' },
        { id: 'az-b', members: ['n-b'], label: 'Availability Zone · us-east-1b' },
        { id: 'az-c', members: ['n-c'], label: 'Availability Zone · us-east-1c' },
      ],
    })),
  },

  {
    name: 'two overlapping nodes',
    because: 'node occlusion — one icon covers the other and the reader does not know there are two',
    expect: ['A3.1'],
    ...build('a3.1', [
      v('a', '1', 100, 100, 78, 78, icon()),
      v('b', '1', 140, 130, 78, 78, icon('#C925D1', 'rds')),
    ], mod([
      { id: 'a', kind: 'service', service: 'lambda' },
      { id: 'b', kind: 'service', service: 'rds' },
    ])),
  },

  {
    name: 'edge passing over a node it does not connect to',
    because: 'node-edge occlusion — the line appears to touch a service it does not touch',
    expect: ['A3.5'],
    ...build('a3.5', [
      v('origin', '1', 60, 160, 78, 78, icon()),
      v('mid', '1', 380, 160, 78, 78, icon('#8C4FFF', 'vpc_endpoints')),
      v('destination', '1', 700, 160, 78, 78, icon('#C925D1', 'rds')),
      e('e1', 'origin', 'destination', 'writes', edge(), [{ x: 250, y: 199 }, { x: 620, y: 199 }]),
    ], mod([
      { id: 'origin', kind: 'service', service: 'lambda' },
      { id: 'mid', kind: 'service', service: 'vpc_endpoints' },
      { id: 'destination', kind: 'service', service: 'rds' },
    ], { edges: [{ from: 'origin', to: 'destination', label: 'writes' }] })),
  },

  {
    name: 'two parallel edges glued to each other',
    because: 'both labels land on the same stroke and neither one reads',
    expect: ['A5.8'],
    ...build('a5.8', [
      v('a', '1', 60, 160, 78, 78, icon()),
      v('b', '1', 600, 160, 78, 78, icon('#C925D1', 'rds')),
      e('e1', 'a', 'b', 'reads', edge(), [{ x: 300, y: 199 }]),
      e('e2', 'a', 'b', 'writes', edge(), [{ x: 300, y: 201 }]),
    ], mod([
      { id: 'a', kind: 'service', service: 'lambda' },
      { id: 'b', kind: 'service', service: 'rds' },
    ], { edges: [{ from: 'a', to: 'b', label: 'reads' }, { from: 'a', to: 'b', label: 'writes' }] })),
  },

  {
    name: 'edges crossing at a shallow angle',
    because: 'Purchase 1997 — crossing is the aesthetic with the largest measured effect, and shallow is the worst kind',
    expect: ['A5.1', 'A5.2'],
    ...build('a5.1', [
      v('a1', '1', 60, 100, 78, 78, icon()),
      v('a2', '1', 60, 300, 78, 78, icon()),
      v('b1', '1', 700, 130, 78, 78, icon('#C925D1', 'rds')),
      v('b2', '1', 700, 270, 78, 78, icon('#C925D1', 'rds')),
      e('e1', 'a1', 'b2', 'one', edge()),
      e('e2', 'a2', 'b1', 'two', edge()),
    ], mod([
      { id: 'a1', kind: 'service', service: 'lambda' }, { id: 'a2', kind: 'service', service: 'lambda' },
      { id: 'b1', kind: 'service', service: 'rds' }, { id: 'b2', kind: 'service', service: 'rds' },
    ], { edges: [{ from: 'a1', to: 'b2', label: 'one' }, { from: 'a2', to: 'b1', label: 'two' }] })),
  },

  {
    name: 'insufficient text contrast',
    because: 'WCAG 2.2 SC 1.4.3 — light gray on white does not reach 4.5:1',
    expect: ['A7.1'],
    ...build('a7.1', [
      v('pale-group', '1', 60, 60, 400, 300, group('#CCCCCC').replace(`fontColor=${GRAY}`, '') + 'fontColor=#BBBBBB;'),
      v('node', 'pale-group', 40, 80, 78, 78, icon().replace(`fontColor=${GRAY}`, 'fontColor=#DDDDDD')),
    ], mod([
      { id: 'pale-group', kind: 'vpc' },
      { id: 'node', kind: 'service', service: 'lambda', inside: 'pale-group' },
    ])),
  },

  {
    name: 'icon fill that vanishes into the background',
    because: 'WCAG 2.2 SC 1.4.11 — the icon\'s silhouette needs 3:1 against what is behind it',
    expect: ['A7.2'],
    ...build('a7.2', [
      // the group border is dark on purpose: if it also failed, the case would
      // pass without proving that the icon's FILL is what is measured
      v('background', '1', 60, 60, 400, 300, group('#595959', '#F2F2F2')),
      v('almost-invisible', 'background', 40, 80, 78, 78, icon('#EFEFEF')),
    ], mod([
      { id: 'background', kind: 'vpc' },
      { id: 'almost-invisible', kind: 'service', service: 'lambda', inside: 'background' },
    ])),
  },

  {
    name: 'dark text on a dark group',
    because: 'the case that the wrong z-cut let through: 1.00:1 on screen turned into 13.57:1 measured against the page. ' +
      'It is the dangerous direction of the bug — the false NEGATIVE, which approves the unreadable',
    expect: ['A7.1'],
    ...build('a7.1-escuro', [
      // group with a dark fill and a label almost the same color
      v('dark-group', '1', 60, 60, 400, 300,
        group('#232F3E', '#232F3D').replace('fontColor=', 'fontColorAntigo=') + 'fontColor=#232F3E;'),
      v('node', 'dark-group', 40, 80, 78, 78, icon()),
    ], mod([
      { id: 'dark-group', kind: 'vpc' },
      { id: 'node', kind: 'service', service: 'lambda', inside: 'dark-group' },
    ])),
  },

  {
    name: 'drawing overflowing the canvas',
    because: 'the `drawio -x` export uses the box that contains everything; what runs past the page becomes a cropped image or a blank band',
    expect: ['A3.7'],
    ...build('a3.7', [
      v('a', '1', 100, 100, 78, 78, icon()),
      v('far', '1', 1400, 100, 78, 78, icon()),
    ], mod([
      { id: 'a', kind: 'service', service: 'lambda' },
      { id: 'far', kind: 'service', service: 'lambda' },
    ]), 600, 400),
  },

  {
    name: 'mirrored icon with a shadow',
    because: 'AWS and Azure forbid deforming the icon; Tufte calls the shadow chartjunk',
    expect: ['A2.2', 'A2.11'],
    ...build('a2.2', [
      v('skewed', '1', 100, 100, 78, 78, icon() + 'flipH=1;shadow=1;'),
      v('straight', '1', 300, 100, 78, 78, icon()),
    ], mod([
      { id: 'skewed', kind: 'service', service: 'lambda' },
      { id: 'straight', kind: 'service', service: 'lambda' },
    ])),
  },

  {
    name: 'unnamed element and a bidirectional edge',
    because: 'C4 — every element named, every line unidirectional',
    expect: ['A1.4', 'A1.7'],
    ...build('a1', [
      v('anonymous', '1', 100, 100, 78, 78, icon(), ''),
      v('other', '1', 400, 100, 78, 78, icon('#C925D1', 'rds')),
      e('e1', 'anonymous', 'other', 'talks to', edge('startArrow=blockThin;startFill=1;')),
    ], mod([
      { id: 'anonymous', kind: 'service', service: 'lambda' },
      { id: 'other', kind: 'service', service: 'rds' },
    ], { edges: [{ from: 'anonymous', to: 'other', label: 'talks to' }] })),
  },

  {
    name: 'two overlapping sibling groups',
    because: 'the AWS hierarchy is a tree; overlapping siblings leave it ambiguous which one contains what',
    expect: ['A4.3'],
    ...build('a4.3', [
      v('vpc-a', '1', 60, 60, 300, 260, group()),
      v('vpc-b', '1', 260, 60, 300, 260, group('#C925D1')),
    ], mod([{ id: 'vpc-a', kind: 'vpc' }, { id: 'vpc-b', kind: 'vpc' }])),
  },

  {
    name: 'child escaping the parent\'s box',
    because: 'strict containment — half the drawn resource is outside the subnet it belongs to',
    expect: ['A4.1'],
    ...build('a4.1', [
      v('vpc', '1', 60, 60, 300, 260, group()),
      v('leaking', 'vpc', 260, 100, 78, 78, icon()),
    ], mod([
      { id: 'vpc', kind: 'vpc' },
      { id: 'leaking', kind: 'service', service: 'lambda', inside: 'vpc' },
    ])),
  },
];

/**
 * The positive control: same vocabulary, correct geometry.
 *
 * It serves to prove that the cases above fail because of the DEFECT and not
 * because of the construction style — if this one also flagged A4.2, what the
 * suite would be measuring is the plan builder, not the validator.
 */
const CONTROL = build('control', [
  v('cloud', '1', 40, 40, 760, 420, group('#232F3E')),
  v('vpc', 'cloud', 20, 46, 480, 340, group()),
  v('sub', 'vpc', 20, 46, 440, 260, group('#00A4A6', '#E6F6F7')),
  v('app', 'sub', 30, 60, 78, 78, icon()),
  v('db', 'sub', 320, 60, 78, 78, icon('#C925D1', 'rds')),
  v('external', 'cloud', 620, 120, 78, 78, icon('#8C4FFF', 'vpc_endpoints')),
  e('e1', 'app', 'db', 'query', edge()),
], mod([
  { id: 'cloud', kind: 'cloud' },
  { id: 'vpc', kind: 'vpc', inside: 'cloud' },
  { id: 'sub', kind: 'subnet', access: 'private', inside: 'vpc' },
  { id: 'app', kind: 'service', service: 'lambda', inside: 'sub' },
  { id: 'db', kind: 'service', service: 'rds', inside: 'sub' },
  { id: 'external', kind: 'service', service: 'vpc_endpoints', inside: 'cloud' },
], { edges: [{ from: 'app', to: 'db', label: 'query', protocol: 'sql' }] }), 900, 560);

module.exports = { CASES, CONTROL };
